version: '3.8'
services:
  # 1. Redis (Optimized)
  redis:
    image: redis:7.2-alpine
    container_name: flight-redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 64M

  # 2. Kafka (KRaft Mode - No Zookeeper!)
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: flight-kafka
    ports:
      - "9092:9092"
    environment:
      # --- KRAFT CONFIGURATION ---
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # Generates a random cluster ID for you
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      # --- OPTIMIZATION (Memory Cap) ---
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    deploy:
      resources:
        limits:
          memory: 512M